name: Automated API tests using Postman CLI

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:
  schedule:
  - cron: '45 9 * * 1-5'

jobs:
  automated-api-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Lint API Spec
        run: |
          postman spec lint "3b7c6f05-73e7-4a85-8004-04d1c39d7294" \
            --workspace-id 9114fc42-1334-402d-986c-1e017e2c7f03 \
            --fail-severity error --output json --report-events
      - name: Run API tests
        run: |
          postman collection run "52509354-1cab5051-40e7-4775-a6a7-539def768210" \
            -e "52509354-91682dc0-966d-4a33-ac89-38f9995a2ae0" --report-events
